import React from 'react';
import { EosCard, Typography } from '@earthos/ui';
import { Leaf, Cpu } from 'lucide-react';
import { ObjectItem } from '../../../services/objectService';

interface ObjectMetricsProps {
  object: ObjectItem;
}

export const ObjectMetrics: React.FC<ObjectMetricsProps> = ({ object }) => {
  return (
    <EosCard variant="glass" className="p-6 flex flex-col gap-5">
      <div className="grid grid-cols-2 gap-6">
        {/* Carbon Impact */}
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-green-500/10 text-green-500 rounded-lg">
              <Leaf size={18} />
            </div>
            <Typography variant="small" className="text-gray-500 font-bold uppercase tracking-wider text-[11px]">Carbon Score</Typography>
          </div>
          <div className="flex items-end gap-2">
            <Typography variant="h2" className="font-bold text-green-500 leading-none">
              {object.carbonScore ?? 0}
            </Typography>
            <Typography variant="small" className="text-gray-400 mb-1 font-semibold">/ 100</Typography>
          </div>
          <div className="w-full bg-gray-100 dark:bg-white/10 h-2 rounded-full overflow-hidden mt-1">
            <div 
              className="h-full bg-gradient-to-r from-green-400 to-green-600 rounded-full" 
              style={{ width: `${object.carbonScore ?? 0}%` }}
            />
          </div>
          <Typography variant="small" className="text-xs text-gray-400 mt-1">
            Environmental impact metric based on material composition and lifecycle.
          </Typography>
        </div>

        {/* AI Score */}
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-blue-500/10 text-blue-500 rounded-lg">
              <Cpu size={18} />
            </div>
            <Typography variant="small" className="text-gray-500 font-bold uppercase tracking-wider text-[11px]">AI Insight Score</Typography>
          </div>
          <div className="flex items-end gap-2">
            <Typography variant="h2" className="font-bold text-blue-500 leading-none">
              {object.aiScore ?? 0}
            </Typography>
            <Typography variant="small" className="text-gray-400 mb-1 font-semibold">/ 100</Typography>
          </div>
          <div className="w-full bg-gray-100 dark:bg-white/10 h-2 rounded-full overflow-hidden mt-1">
            <div 
              className="h-full bg-gradient-to-r from-blue-400 to-blue-600 rounded-full" 
              style={{ width: `${object.aiScore ?? 0}%` }}
            />
          </div>
          <Typography variant="small" className="text-xs text-gray-400 mt-1">
            Overall health and utility assessment generated by EarthOS AI models.
          </Typography>
        </div>
      </div>
    </EosCard>
  );
};
